branches:
  only:
    - master
    - /^greenkeeper/.*$/
language: node_js
node_js :
 - stable
install:
 - npm install
script:
  - "npm test"
after_success: 
  - "npm run coverage"
notifications:
  email: false
after_script:
  - cat ./coverage/lcov.info | ./node_modules/.bin/codeclimate
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
